//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PETslnslnslnslnslnsln
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informants
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int PaymentID { get; set; }
    
        public virtual Payments Payments { get; set; }
        public virtual Persons Persons { get; set; }
    }
}
