//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PETslnslnslnslnslnsln
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PETDBEntities : DbContext
    {
        public PETDBEntities()
            : base("name=PETDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<Currencies> Currencies { get; set; }
        public virtual DbSet<Informants> Informants { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Nationalities> Nationalities { get; set; }
        public virtual DbSet<ObservantGroups> ObservantGroups { get; set; }
        public virtual DbSet<Observants> Observants { get; set; }
        public virtual DbSet<Observations> Observations { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
    }
}
